name: Hello World Commit

on:
  workflow_dispatch:

  #pull_request:
    #branches:
     # - "main"
    #paths:
     # - ".github/workflows/"

permissions:
  contents: write

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main 
          # for starting from a known state
          # branch protection rules - ensures the workflow respect the protection rules
          # avoids detached HEAD which can lead to instability/confusion
          # ensures branch has the latest code/version

      - name: Generate a random branch name and create it
        run: |
          branch_name="feature-$(date +"%d-%m-%Y-%H-%M")"

          # Create and switch to the new branch
          git checkout -b $branch_name
          echo "Created and switched to new branch: $branch_name"

      - name: Echo Hello World and save to file hello_world.txt
        run: |
          current_date=$(date +"%d-%m-%Y-%H-%M") 
          echo "Hello World" > hello_world_$current_date.txt

      - name: Commit and Push changes to repo
        run: |
          #branch_name=$(git rev-parse --abbrev-ref HEAD) # Get the current branch name
          current_date=$(date +"%d-%m-%Y-%H-%M")
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hello_world_$current_date.txt
          git commit -m "Added hello_world_$current_date.txt"
          git push --set-upstream origin $branch_name


