name: Hello World Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Hello World and save to file hello_world.txt
        run: |
          current_date=$(date+"%d/%m/%Y") 
          echo "Hello World" > hello_world_$current_date.txt

      - name: Commit and Push changes to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hello_world.txt
          git commit -m "Added hello_world.txt"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git


